## 02.텐서 조작하기(Tensor Manipulation) 1

이번 챕터에서 배울 내용에 대해서 리뷰해보겠다.

벡터, 행렬, 텐서의 개념에 대해서 이해하고, Numpy와 파이토치로 벡터, 행렬, 텐서를 다루는 방법에 대해서 이해한다.

* **벡터, 행렬 그리고 텐서(Vector, Matrix and Tensor)**
> 딥러닝을 위한 가장 기본적인 수학적 지식인 벡터, 행렬, 텐서에 대해서 알아본다.

* **넘파이 훑어보기(Numpy Review)**
> 파이토치는 파이썬 패키지 넘파이(Numpy)와 유사하다. 따라서 넘파이에 대해서 간단히 살펴보겠다.

* **파이토치 텐서 선언하기(PyTorch Tensor Allocation)**
> 넘파이로 실습을 해보았다. 이제 파이토치 텐서 선언 방법에 대해서 알아본다.

* **행렬 곱셈(Matrix Multiplication)**
> 행렬 연산에 대해서 이해한다.

* **다른 오퍼레이션들(Other Basic Ops)**
> 다른 기본적인 오퍼레이션들에 대해서 이해해본다.

### 1.벡터, 행렬 그리고 텐서(Vector, Matrix and Tensor)



#### 1) 벡터, 행렬, 텐서 그림으로 이해하기

<img src = 'https://wikidocs.net/images/page/52460/tensor1.PNG' width = 60%>

딥러닝을 하게 되면 다루게 되는 가장 기본적인 단위는 벡터, 행렬, 텐서이다. 차원이 없는 값을 스칼라(위의 그림에는 없음), 1차원으로 구성된 값을 우리는 벡터라고 한다.

2차원으로 구성된 값을 행렬(Matrix)라고 한다. 그리고 3차원이 되면 우리는 텐서(Tensor)라고 부른다. 사실 우리는 3차원의 세상에 살고 있으므로, 4차원 이상부터는 머리로 생각하기는 어렵다. 4차원은 3차원의 텐서를 위로 쌓아 올린 모습으로 상상해보겠다.

5차원은 그 4차원을 다시 옆으로 확장한 모습으로 생각해보자. 6차원은 5차원을 뒤로 확장한 모습으로 볼 수 있다.

* **옮긴이 주 : 데이터사이언스 분야 한정으로 3차원 이상의 텐서는 그냥 다차원 행렬 또는 배열로 간주할 수 있다. 또한 주로 3차원 이상을 텐서라고 하긴 하지만, 1차원 벡터나 2차원인 행렬도 텐서라고 표현하기도 한다. 같은 표현이다. 1차원 벡터 = 1차원 텐서, 2차원 행렬 = 2차원 텐서, 그리고 3차원 텐서, 4차원 텐서, 5차원 텐서 등...**



#### 2) PyTorch Tensor Shape Convection

사실 딥러닝을 할 때 다루고 있는 행렬 또는 텐서의 크기를 고려하는 것은 항상 중요하다. 여기서는 앞으로 행렬과 텐서의 크기를 표현할 때 다음과 같은 방법으로 표기한다. 앞으로 다루게 될 텐서 중 가장 전형적인 2차원 텐서를 예로 들어보자.

* **2D Tensor(Typical Simple Setting)

|t| = (Batch size, dim)

<img src = 'https://wikidocs.net/images/page/52460/tensor2.PNG'>

위의 경우는 2차원 텐서의 크기 |t|를 (batch_size x dimension)으로 표현하였을 경우이다. 조금 쉽게 말하면, 아래의 그림과 같이 행렬에서 행의 크기가 batch_size, 열의 크기가 dim이라는 의미이다.

<img src = 'https://wikidocs.net/images/page/52460/tensor3.PNG'>

* **옮긴이 주 : 훈련 데이터 하나의 크기를 256이라고 해보자. [3, 1, 2, 5, ...] 이런 숫자들의 나열이 256의 길이로 있다고 상상하면 된다. 다시 말해 훈련 데이터 하나 = 벡터의 차원은 256이다. 만약 이런 훈련 데이터의 개수가 3000개라고 한다면, 현재 전체 훈련 데이터의 크기는 3,000 x 256이다. 행렬이니까 2D 텐서이다. 3,000개를 1개씩 꺼내서 처리하는 것도 가능하지만 컴퓨터는 훈련 데이터를 하나씩 처리하는 것보다 보통 덩어리로 처리한다. 3,000개에서 64개씩 꺼내서 처리한다고 한다면 이 때 batch size를 64라고 한다. 그렇다면 컴퓨터가 한 번에 처리하는 2D 텐서의 크기는 (batch size x dim) = 64 x 256이다.**

* **3D Tensor(Typical Computer Vision) - 비전 분야에서의 3차원 텐서**

|t| = (batch size, width, height)

<img src = 'https://wikidocs.net/images/page/52460/tensor4.PNG'>

일반적으로 자연어 처리보다 비전 분야(이미지, 영상 처리)를 하게 된다면 좀 더 복잡한 텐서를 다루게 된다. 이미지라는 것은 가로, 세로라는 것이 존재한다. 그리고 여러 장의 이미지, 그러니까 batch size로 구성하게 되면 아래와 같이 3차원의 텐서가 된다.

<img src = 'https://wikidocs.net/images/page/52460/tensor5.PNG'>

위의 그림은 세로는 batch size, 가로는 너비(width), 그리고 안쪽으로는 높이(height)가 되는 것을 보여준다.

* **3D Tensor(Typical Natural Language Processing) - NLP 분야에서의 3차원 텐서**

|t| = (batch size, length, dim)

<img src = 'https://wikidocs.net/images/page/52460/tensor4.PNG'>

자연어 처리는 보통 (batch size, 문장 길이, 단어 벡터의 차원)이라는 3차원 텐서를 사용한다.

<img src = 'https://wikidocs.net/images/page/52460/tensor6.PNG'>

* **NLP 분야의 3D 텐서 예제로 이해하기 - 옮긴이**

아래와 같이 4개의 문장으로 구성된 전체 훈련 데이터가 있다.

> [[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]

컴퓨터는 아직 이 상태로는 '나는 사과를 좋아해'가 단어가 1개인지 3개인지 이해하지 못한다. 우선 컴퓨터의 입력으로 사용하기 위해서는 단어별로 나눠주어야 한다.

> [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]

이제 훈련 데이터의 크기는 4 x 3의 크기를 가지는 2D 텐서이다. 컴퓨터는 텍스트보다는 숫자를 더 잘 처리할 수 있다. 이제 각 단어를 벡터로 만들 것이다. 아래와 같이 단어를 3차원의 벡터로 변환했다고 하겠다.

> '나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6, 0.5]
'싫어해' = [0.5, 0.6, 0.7]

위 기준을 따라서 훈련 데이터를 재구성하면 아래와 같다.

> [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

이제 훈련 데이터는 4 x 3 x 3의 크기를 가지는 3D 텐서이다. 이제 batch size를 2로 해보겠다.

> 첫번째 배치 #1

> [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],

> [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

> 두번째 배치 #2

> [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],

> [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

컴퓨터는 배치 단위로 가져가서 연산을 수행한다. 그리고 현재 각 배치의 텐서의 크기는 (2 x 3 x 3)이다. 이는 (batch size, 문장 길이, 단어 벡터의 차원)의 크기이다.




### 2.넘파이로 텐서 만들기 (벡터와 행렬 만들기)

PyTorch로 텐서를 만들어보기 전에 우선 Numpy로 텐서를 만들어보겠다. 우선 numpy를 임포트한다.

In [1]:
import numpy as np

Numpy로 텐서를 만드는 방법은 간단한데 [숫자, 숫자, 숫자]와 같은 형식으로 만들고 이를 np.array()로 감싸주면 된다.

#### 1) 1D with Numpy

Numpy로 1차원 벡터를 만들어보겠다.

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


이제 1차원 벡터의 차원과 크기를 출력해보겠다.


In [3]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


.ndim은 몇 차원인지를 출력한다. 1차원은 벡터, 2차원은 행렬, 3차원은 3차원 텐서였다. 현재는 벡터이므로 1차원이 출력된다. .shape는 크기를 출력한다. (7, )는 (1, 7)을 의미한다. 다시 말해 (1 x 7)의 크기를 가지는 벡터이다.

* **옮긴이 주 : 텐서의 크기(shape)를 표현할 때는 ,(컴마)를 쓰기도 하고 x(곱하기)를 쓰기도 한다. 예를 들어 2행 3열의 2D 텐서를 표현할 때 (2, 3)라고 하기도 하고 (2 x 3)이라고 하기도 한다. (5, )의 형식은 (1 x 5)를 의미한다.**



##### 1-1) Numpy 기초 이해하기

이제 Numpy에서 각 벡터의 원소에 접근하는 방법을 알아보겠다. Numpy에서 인덱스는 0부터 시작한다.



In [5]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] = 0.0 1.0 6.0


위의 결과는 0번 인덱스를 가진 원소인 0.0, 1번 인덱스를 가진 원소인 1.0, -1번 인덱스를 가진 원소인 6.0이 출력되는 것을 보여준다. -1번 인덱스는 맨 뒤에서부터 시작하는 인덱스이다.

범위 지정으로 원소를 불러올 수도 있다. 이를 슬라이싱(Slicing)이라고 한다. 사용 방법은 [시작 번호 : 끝 번호]를 통해 사용한다. 주의할 점은 슬라이싱은 [시작 번호 : 끝 번호]라고 했을 때, 끝 번호에 해당하는 것은 포함하지 않는다.



In [6]:
print('t[2:5] t[4:-1] =', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.


t[2:5] t[4:-1] = [2. 3. 4.] [4. 5.]


위의 슬라이싱의 결과를 보겠다. [2:5]라고 한다면 2번 인덱스부터 4번 인덱스까지의 결과를 가져온다는 의미이다. [4:-1]은 4번 인덱스부터 끝에서 첫번째 것까지의 결과를 가져온다는 의미이다.

시작 번호 또는 끝 번호를 생략해서 슬라이싱을 하기도 한다. [시작 번호 : 끝 번호]에서 시작 번호를 생략하면 처음부터 끝 번호까지 뽑아낸다. 반면에 [시작 번호 : 끝 번호]에서 끝 번호를 생략하면 시작 번호부터 끝까지 뽑아낸다.

In [7]:
print('t[:2] t[3:] =', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우


t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


#### 2) 2D with Numpy

Numpy로 2차원 행렬을 만들어보겠다.

In [8]:
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],
              [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank  of t:', t.ndim)
print('Shape of t:', t.shape)

Rank  of t: 2
Shape of t: (4, 3)


.ndim은 몇 차원인지를 출력한다. 1차원은 벡터, 2차원은 행렬, 3차원은 3차원 텐서였다. 현재는 행렬이므로 2차원이 출력된다. .shape는 크기를 출력한다. (4, 3)이다. 다른 표현으로는 (4 x 3)이다. 이는 행렬이 4행 3열임을 의미한다.

Numpy로도 3차원 텐서도 만들 수는 있지만 이 시점에서 Numpy와 PyTorch를 비교하기 위해 PyTorch로 실습을 넘어간다.

### 3.파이토치 텐서 선언하기(PyTorch Tensor Allocation)

파이토치는 Numpy와 매우 유사하다. 하지만 더 낫다(better). 우선 torch를 임포트한다.


In [10]:
import torch

Numpy를 사용하여 진행했던 실습을 파이토치로 똑같이 해보자.

#### 1) 1D with PyTorch

파이토치로 1차원 벡터를 만들어보자.

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


dim()을 사용하면 현재 텐서의 차원을 보여준다. shape나 size()를 사용하면 크기를 확인할 수 있다.

In [12]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


현재 1차원 텐서이며, 원소는 7개이다. 인덱스로 접근하는 것과 슬라이싱을 해보자. 방법은 Numpy 실습과 같다.

In [13]:
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1])   # 슬라이싱
print(t[:2], t[3:])      # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#### 2) 2D with PyTorch

파이토치로 2차원 행렬을 만들어보자.

In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


dim()을 사용하면 현재 텐서의 차원을 보여준다. size()를 사용하면 크기를 확인할 수 있다.

In [15]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


현재 텐서의 차원은 2차원이며, (4, 3)의 크기를 가진다. 슬라이싱을 해보자.

In [16]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


위의 결과는 첫번째 차원을 전체 선택하고, 그 상황에서 두번째 차원의 1번째 인덱스 값만을 가져온 경우를 보여준다. 다시 말해 텐서에서 두번째 열에 있는 모든 값을 가져온 상황이다. 그리고 이렇게 값을 가져온 경우의 크기는 4이다. (1차원 벡터)



In [18]:
# 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.
print(t[:, :-1]) 


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


위의 결과는 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져오는 경우이다.

#### 3) 브로드캐스팅(Broadcasting)

두 행렬 A, B가 있다고 해보자. 행렬의 덧셈과 뺄셈에 대해 알고 있다면, 이 덧셈과 뺄셈을 할 때에는 두 행렬 A, B의 크기가 같아야 한다는 것을 알고 있을 것이다. 그리고 두 행렬이 곱셈을 할 때에는 A의 마지막 차원과 B의 첫번째 차원이 일치해야 한다.

물론, 이런 규칙들이 있지만 딥러닝을 하게되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우가 생긴다. 이를 위해 파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 **브로드캐스팅**이라는 기능을 제공한다.

우선 같은 크기일 때 연산을 하는 경우를 보겠다.

In [19]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


여기서 m1과 m2의 크기는 둘 다 (1, 2)이다. 그래서 문제없이 덧셈 연산이 가능하다. 이번에는 크기가 다른 텐서들 간의 연산을 보겠다. 아래는 벡터와 스칼라가 덧셈 연산을 수행하는 것을 보여준다. 물론, 수학적으로는 원래 연산이 안 되는게 맞지만 파이토치에서는 브로드캐스팅을 통해 이를 연산한다.

In [20]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


원래 m1의 크기는 (1, 2)이며 m2의 크기는 (1, )이다. 그런데 파이토치는 m2의 크기를 (1, 2)로 변경하여 연산을 수행한다. 이번에는 벡터 간 연산에서 브로드캐스팅이 적용되는 경우를 보겠다.

In [21]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


m1의 크기는 (1, 2), m2의 크기는 (2, 1)이었다. 이 두 벡터는 원래 수학적으로는 덧셈을 수행할 수 없다. 그러나 파이토치는 두 벡터의 크기를 (2, 2)로 변경하여 덧셈을 수행한다.

``` python
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```

브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 사용자 입장에서 굉장히 주의해서 사용해야 한다. 예를 들어 A 텐서와 B 텐서가 있을 때, 사용자는 이 두 텐서의 크기가 같다고 착각하고 덧셈 연산을 수행했다고 가정해보겠다. 하지만 실제로 이 두 텐서의 크기를 달랐고 브로드캐스팅이 수행되어 덧셈 연산이 수행되었다. 만약, 두 텐서의 크기가 다르다고 에러를 발생시킨다면 사용자는 이 연산이 잘못되었음을 바로 알 수 있지만 브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않았더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있다.


#### 4) 자주 사용되는 기능들



##### 1) 행렬 곱셈과 곱셈의 차이 (Matrix Multiplication vs Multiplication)

행렬로 곱셈을 하는 방법은 크게 두 가지가 있다. 바로 행렬 곱셈(.matmul)과 원소 별 곱셈(.mul)이다.

파이토치 텐서의 행렬 곱셈을 보겠다. 이는 matmul()을 통해 수행한다. 

In [22]:
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix 1:', m1.shape) # 2 x 2
print('Shape of Matrix 2:', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


위의 결과는 2 x 2 행렬과 2 x 1 행렬(벡터)의 행렬 곱셈의 결과를 보여준다.

행렬 곱셈이 아니라 element-wise 곱셈이라는 것이 존재한다. 이는 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 말한다. 아래는 서로 다른 크기의 행렬이 브로드캐스팅이 된 후에 element-wise 곱셈이 수행되는 것을 보여준다. 이는 * 또는 mul()을 통해 수행한다.



In [24]:
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix 1:', m1.shape) # 2 x 2
print('Shape of Matrix 2:', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


m1 행렬의 크기는 (2, 2)이었다. m2 행렬의 크기는 (2, 1)이었다. 이때 element-wise 곱셈을 수행하면, 두 행렬의 크기는 브로드캐스팅이 된 후에 곱셈이 수행된다. 더 정확히는 여기서 m2의 크기가 변환된다.

``` python
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
[1]
[2]
==> [[1, 1],
     [2, 2]]
```



##### 2) 평균(Mean)

평균을 구하는 방법도 제공하고 있다. 이는 Numpy에서의 사용법과 매우 유사하다.

우선 1차원인 벡터를 선언하여 .mean()을 사용하여 원소의 평균을 구한다.

In [25]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


1과 2의 평균인 1.5가 나온다. 이번에는 2차원인 행렬을 선언하여 .mean()을 사용해보자. 우선 2차원 행렬을 선언한다.

In [31]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


2차원 행렬이 선언되었다. 이제 .mean()을 사용한다.

In [32]:
print(t.mean())

tensor(2.5000)


4개의 원소의 평균인 2.5가 나왔다. 이번에는 dim. 즉, 차원(dimension)을 인자로 주는 경우를 보겠다.

In [33]:
print(t.mean(dim = 0))

tensor([2., 3.])


dim = 0이라는 것은 첫번째 차원을 의미한다. 행렬에서 첫번째 차원은 '행'을 의미한다. 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 된다. 다시 말해 행렬에서 '열'만 남기겠다는 의미가 된다. 기존 행렬의 크기는 (2, 2)였지만 이를 수행하면 열의 차원만 보존되면서 (1, 2)가 된다. 이는 (2, )와 같으며 벡터이다. 열의 차원은 보존하면서 평균을 구하면 아래와 같이 연산한다.

``` python
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
```

이번에는 인자로 dim = 1을 주겠다. 이번에는 두번째 차원을 제거한다. 즉, 열이 제거된 텐서가 되어야 한다.



In [34]:
print(t.mean(dim = 1))

tensor([1.5000, 3.5000])


열의 차원이 제거되어야 하므로 (2, 2)의 크기에서 (2, 1)의 크기가 된다. 이번에는 1과 3의 평균을 구하고 3과 4의 평균을 구하게 된다. 그렇다면 결과는 아래와 같다.

``` python
# 실제 연산 결과는 (2 × 1)
[1. 5]
[3. 5]
```

하지만 (2 x 1)은 결국 1차원이므로 (1 x 2)와 같이 표현되면서 위와 같이 [1.5, 3.5]로 출력된다. 이번에는 dim = -1를 주는 경우를 보겠다. 이는 마지막 차원을 제거한다는 의미이고, 결국 열의 차원을 제거한다는 의미와 같다. 그러므로 위와 출력 결과가 같다.


In [35]:
print(t.mean(dim = -1))

tensor([1.5000, 3.5000])


##### 3) 덧셈(Sum)

덧셈(Sum)은 평균(Mean)과 연산 방법이나 인자가 의미하는 바는 정확히 동일하다. 다만, 평균이 아니라 덧셈을 할 뿐이다.

In [36]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim = 0)) # 행을 제거
print(t.sum(dim = 1)) # 열을 제거
print(t.sum(dim = -1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


##### 4) 최대(Max)와 아그맥스(ArgMax)

최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴한다.

(2, 2) 크기의 행렬을 선언하고 Max를 사용해보자.

In [38]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


우선 (2, 2) 행렬을 선언하였다. 이제 .max()를 사용한다.

In [39]:
print(t.max()) # Returns one value : max


tensor(4.)


원소 중 최대값인 4를 리턴한다.
이번에는 인자로 dim = 0을 주겠다. 첫번째 차원을 제거한다는 의미이다.

In [40]:
print(t.max(dim = 0)) # Returns two values : max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


행의 차원을 제거한다는 의미이므로 (1, 2) 텐서를 만든다. 결과는 [3, 4]이다.

그런데 [1, 1]이라는 값도 함께 리턴되었다. max에 dim 인자를 주면 argmax도 함께 리턴하는 특징 때문이다. 첫번째 열에서 3의 인덱스는 1이었다. 두번째 열에서 4의 인덱스는 1이었다. 그러므로 [1, 1]이 리턴된다. 어떤 의미인지는 아래 설명해보았다.

``` python
# [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
[[1, 2],
 [3, 4]]
첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
다시 말해 3과 4의 인덱스는 [1, 1]입니다.
```

만약 두 개를 함께 리턴받는 것이 아니라 max 또는 argmax만 리턴받고 싶다면 다음과 같이 리턴값에도 인덱스를 부여하면 된다. 0번 인덱스를 사용하면 max 값만 받아올 수 있고, 1번 인덱스를 사용하면 argmax 값만 받아올 수 있다.


In [41]:
print('Max   :', t.max(dim = 0)[0])
print('Argmax:', t.max(dim = 0)[1])

Max   : tensor([3., 4.])
Argmax: tensor([1, 1])


이번에는 dim = 1로 인자를 주었을 때와 dim = -1로 인자를 주었을 때를 보겠다.

In [42]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


* **슬라이싱에 대한 다른 예제 : https://wikidocs.net/13**

* **PyTorch 텐서에 대한 다양한 예제 : https://datascienceschool.net/view-notebook/4f3606fd839f4320a4120a56eec1e228/**